name: ci
on:
  push:
    branches:
      - 'master'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
<<<<<<< HEAD
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/webscraper:latest
=======
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/webscraper:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/webscraper:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/webscraper:buildcache,mode=max
>>>>>>> ac92ec477e6449e8dd75d49817d9836dec3984ff
